### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by dawnerd** [meilisearch/instant-meilisearch#18] opened 2020-08-03 05:51 UTC
Noticed pagination stops working (with react) once you go past the number of items fetched initially and there's no future offset sent to grab more pages. Not sure if this is by design, but it feels more like an oversight.

I've modified my local copy like so:

```js
transformToMeiliSearchParams: function (params) {
      const searchInput = {
        q: params.query,
        facetsDistribution: params.facets.length ? params.facets : undefined,
        facetFilters: params.facetFilters,
        attributesToHighlight: this.attributesToHighlight,
        limit: this.limitPerRequest,
        offset: params.page * this.limitPerRequest
      }
      return removeUndefinedFromObject(searchInput)
    },
```

And removed the page check/splice in `parseHits`. That splice functionality could probably stay if you detected how many were grabbed at a time and the per page limit and did some calculations on that.

**Comment by curquiza** [comment] 2020-08-06 14:36
Hello @dawnerd, thanks for your report 🙂

I'm don't really understand the issue, but I might have found one concerning pagination (on React only). I notice there is a missing arrow at the bottom of the page:

<img width="854" alt="Capture d’écran 2020-08-06 à 16 33 44" src="https://user-images.githubusercontent.com/20380692/89544904-f62e8700-d802-11ea-9d83-c729d862da04.png">

Is this your issue? 🙂

**Comment by dawnerd** [comment] 2020-08-09 18:16
Can confirm new version fixed the other issue but not pagination yet

**Comment by curquiza** [comment] 2020-08-10 08:07
Hello @dawnerd!

I haven't merged the PR that fixes the pagination yet, see #31.
Can you confirm that the problem I describe is the same problem you noticed? Because I'm not sure to exactly understand the pagination issue you have.

**Comment by curquiza** [comment] 2020-08-10 14:50
@dawnerd 
If your issue is the same issue I described, please replace:

```js
<Pagination />
```
by
```js
<Pagination showLast={true} />
```

The [react codesandbox](https://codesandbox.io/s/ms-react-is-sh9ud?file=/src/App.js) is now up-to-date.

**Comment by dawnerd** [comment] 2020-08-10 15:43
Nope, didn't help. Your sandbox is still capped at paginating a max of 50 items - solution was in the code block I pasted above.

Every click on a pagination item in the sandbox also returns the same response.

**Comment by curquiza** [comment] 2020-08-11 09:05
> Every click on a pagination item in the sandbox also returns the same response.

I'm a little bit confused because I don't have this problem when using the codesandbox... It's complicated to fix something I don't succeed to reproduce 😕

**Comment by curquiza** [comment] 2020-08-11 09:27
> Your sandbox is still capped at paginating a max of 50 items

This is normal, the `limitPerRequest` is by default set to 50.
If you want to change that, see [these docs](https://github.com/meilisearch/instant-meilisearch/#customization).

But maybe the `limitPerRequest` name is confusing... because we indeed re-do a request when clicking on the pagination items... `limitPerRequest` is the number of total item.
Maybe it would deserve a better name, like `totalResults` or `totalPages` (and I would need to change my code in this second option of course).

**Comment by dawnerd** [comment] 2020-08-11 14:50
A re request is exactly what we need. It doesn’t make sense to only return 50 items max, and if I wanted to let someone Latinate over say 200, it also doesn’t make sense to pull in 200 in one request. But there’s still the issue that it’s making the request on every pagination click regardless, check the network tab.

**Comment by curquiza** [comment] 2020-08-11 16:06
Hope this time I understand well your issue, not easy so far…

MeiliSearch does not handle pagination yet. I mean, I have no way with MeiliSearch to know the exact number of hits for a query. There is always a limit (20 by default).
The pagination handles by InstantSearch is a **finite** pagination. It means I have to provide the total number of pages. See [this line](https://github.com/meilisearch/instant-meilisearch/blob/462aa00a8b29ce82cdd16f9e94916706076484c7/src/index.js#L70).
That's why I increase the number of hits (`limit`).
So, I cannot use the `offset` of MeiliSearch otherwise I wouldn’t get any total of pages to provide to InstantSearch.

I know this is not performant with the current solution but since MeiliSearch does not provide enough information to handle the pagination.

**Comment by dawnerd** [comment] 2020-08-11 16:20
It works with my patch above so I dunno, I can paginate through all of the results without issue.

If you look here https://opencoaster.com/ , open up the network tab and search for `a` you can paginate through all of the results - pay attention to the nbHits response var.

**Comment by curquiza** [comment] 2020-08-12 07:53
Yes as you noticed, with your patch you get infinite pagination and not a **finite** one. The InstantSearch pagination widget is not designed for infinite pagination, you maybe don't care but that's not the first purpose of the widget and maybe other users expect the basic behavior.
I'm aware of this pagination issue anyway and be sure I really want to fix that. I will indeed discuss it with the team to find a solution soon. First I'm going to talk with the core-engine team to see if MeiliSearch API could handle pagination in the future.
Otherwise, we should indeed think about a kind of infinite pagination you suggested after discussing the best way to handle it with my team.
For the first version of this plugin, we are just keeping the basic behavior of InstantSearch library but be sure it will change soon.

**Comment by dawnerd** [comment] 2020-08-12 15:10
That’s fair but you’re still making the same request on every pagination click which is a waste of bandwidth and server resources. 

I can totally get behind adding a total cap on items but the default is far too low and will confuse people. If I opt for higher it shouldn’t pull that max all at once especially when MeiliSearch has offset built in that from my tested with large test datasets is just as fast. 

But as it is right now you’re definitely not following the instant search spec, so guess I’ll have to keep my own fork going.

**Comment by curquiza** [comment] 2020-08-12 15:29
> That’s fair but you’re still making the same request on every pagination click which is a waste of bandwidth and server resources.

Yes, I got it: that's the main problem we are discussing here. But as I told you if we want finite pagination we have no choice right now.

> But as it is right now you’re definitely not following the instant search spec

I told you I will discuss it with the different teams. I'm not going to forget this issue. You can understand I cannot afford to work immediately on something that might concern changes on the core-engine or approval of the integration team since it differs from the original behavior of InstantSearch.js.
We are sorry you have to use your fork for the beginning, but please just be patient and be nice, we are doing our best on this package. I'm not going to let the issue open and never come back.
Thanks for your patient!

**Comment by curquiza** [comment] 2020-11-05 14:51
For those who are following this issue.
The [widget pagination](https://www.algolia.com/doc/api-reference/widgets/pagination/js/) of InstantSearch is definitely done for finite pagination. The widget expects a number of pages, and not to provide this information leads to an inconsistent component. For infinite pagination, the [`infiniteHits` option](https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/) should be checked.

The pagination in MeiliSearch is not as obvious as expected. Indeed, MeiliSearch is not designed for finished paginations.
If you want to create finished pagination you indeed need to set a limit of results during your search (when using instant-meilisearch, the parameter `paginationTotalHits` does it for you). MeiliSearch is designed to fastly retrieve the best matching documents (the 20 firsts in a basic search request) but not to return the exact and exhaustif number of documents matching your request, for performance reasons.
Even using an `offset` with a too big value can lead to performance issues: doing a search request with an offset of 1000 and a limit of 10 is equivalent to say "find me the 1010 best documents, and give me the 10 worst ones of this subset".

So, even if MeiliSearch provides an interface to use directly a finish pagination (instead of doing it as we've done right now in our instant-meilisearch codebase), the internal "trick" done in the MeiliSearch codebase would be exactly the same we are doing right now in the instant-meilisearch codebase.

Algolia has the same pagination issue and set a limit by default (1000) to browse during the search, see:
- https://www.algolia.com/doc/api-reference/widgets/pagination/js/#about-this-widget
- https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/pagination/#pagination-limitations

Depending on your dataset, if your documents are big and there are a lot of documents, you could adjust the value of `paginationTotalHits` to create the finished pagination you wish with fewer performance issues as possible.
To know more about MeiliSearch and pagination, since we don't have any tutorial or official guide for the moment, you can check out [this issue](https://github.com/meilisearch/documentation/issues/561).

I close this issue since we cannot make finished pagination better.

**Closed by curquiza** 2020-11-05 14:51 UTC
Labels: MS improvement needed, instant-meilisearch
